### ISSUE TITLE
adding 2 digits to each component of the digital clock.

### ISSUE THREAD

**Issue by onkarsrivastava** [apu52/Temperature_Converter#1]
the digital clock rn appears unsymmetrical whenever we have hour or minute or seconds between 0 - 9. It would look better if all 3 components of clock had 2 compulsory digits assigned .
For eg - It would look like 12:03:05 instead of the current 12:3:5 .

**Comment by onkarsrivastava** [comment]
@apu52 Can i get assigned to it.

**Comment by apu52** [comment]
@onkarsrivastava Welcome to the world of Contribution!

**Comment by apu52** [comment]
@onkarsrivastava you can fix the issue what You have already mentioned. But you can also try to add a clock logo & make changes in the format of the time zone also. btw happy Developing!

**Comment by apu52** [comment]
@onkarsrivastava Are you in any open source programme?

**Comment by onkarsrivastava** [comment]
No, i just started it a few days ago out of sheer boredom

**Comment by onkarsrivastava** [comment]
Do you know of any Open source programmes i can contribute to.I really need some exposure to the world of Open source

**Comment by apu52** [comment]
I am now a part of GSSOC as well as SSOC open source programmes. But it has now come to an end this month

**Comment by apu52** [comment]
You can also apply for winter code season of Google, Hactober fest etc. in this year

**Comment by onkarsrivastava** [comment]
ohk thanks
